name: Build Fortran Executables

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Homebrew
      run: |
        if [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
          sudo apt-get update
          sudo apt-get install -y build-essential curl file git
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> $GITHUB_ENV
        elif [[ ${{ matrix.os }} == 'macos-latest' ]]; then
          brew update
        fi

    - name: Set Up Homebrew Path
      run: |
        if [[ ${{ matrix.os }} == 'ubuntu-latest' ]]; then
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> ~/.bashrc
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        fi
      shell: bash

    - name: Install Dependencies via Homebrew
      run: |
        brew install gcc json-fortran

    - name: Build Executable
      run: |
        chmod +x build.sh
        ./build.sh

    - name: Move Executable
      run: |
        mv seidart src/executables/${{ matrix.os }}

    - name: Upload Executable Artifact
      uses: actions/upload-artifact@v3
      with:
        name: seidart_executables_${{ matrix.os }}
        path: src/executables/${{ matrix.os }}
