name: SeidarT Build For Linux

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, macos-12]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        activate-environment: seidart
        environment-file: seidart-environment.yml
        auto-activate-base: false

    - name: Verify Conda installation
      run: conda info

    - name: Activate Conda environment
      run: conda activate seidart

    - name: Run bash script
      run: |
        bash ./build.sh -b build
    
    - name: Checkout SeidarT repo
      uses: actions/checkout@v2
      with:
        repository: UMainedynamics/SeidarT
        token: ${{ secrets.API_TOKEN_GITHUB2 }}
        path: SeidarT

    - name: Copy binaries
      run: |
        mkdir -p SeidarT/src/seidart/binaries
        cp -r build/* SeidarT/src/seidart/binaries/

    - name: Commit and push binaries
      run: |
        cd SeidarT
        git config --global user.email "stevenbernsen@gmail.com"
        git config --global user.name "sbernsen"
        git add src/seidart/binaries
        git commit -m "Add built binaries"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB2 }}

