name: SeidarT Build For Linux

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        activate-environment: seidart
        environment-file: seidart-environment.yml
        auto-activate-base: false

    - name: Verify Conda installation
      run: conda info

    - name: Activate Conda environment
      run: conda activate seidart

    - name: Run bash script
      run: |
        bash ./build.sh -b build
    
    - name: Configure Git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Clone Repository
      run: git clone https://github.com/UMainedynamics/SeidarT.git

    - name: Copy Binary and Push
      run: |
        cp build/seidartfdtd* SeidarT/src/seidart/binaries
        cd SeidarT
        git add src/seidart/binaries/seidartfdtd*
        git commit -m "Update precompiled binary"
        git push https://${GITHUB_TOKEN}@github.com/UMainedynamics/SeidarT.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}