name: SeidarT Build For Linux

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        activate-environment: seidart
        environment-file: seidart-environment.yml
        auto-activate-base: false

    - name: Verify Conda installation
      run: conda info

    - name: Activate Conda environment
      run: conda activate seidart

    - name: Run bash script
      run: |
        bash ./build.sh -b build
    
    - name: Configure and Push to SeidarT Repository
      uses: sbernsen/github-action-push-to-another-reposotory@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        source-directory: 'build'
        destination-github-username: 'sbernsen'
        destination-repository-name: 'SeidarT'
        user-email: stevenbernsen@gmail.com
        target-branch: main
      # run: |
      #   git config --global user.email "github-actions@github.com"
      #   git config --global user.name "GitHub Actions"
      #   git config --global url."https://".insteadOf git://
      #   git remote set-url origin https://github.com/UMainedynamics/SeidarT.git

      #   cp build/seidartfdtd* SeidarT/src/seidart/binaries
      #   cd SeidarT
      #   git add src/seidart/binaries/seidartfdtd*
      #   git commit -m "Update precompiled binary for ${{ matrix.os }}"        
      #   git push https://${GITHUB_TOKEN}@github.com/UMainedynamics/SeidarT.git
      
