name: Create SeidarT Environment

on: [push]

jobs:
  build-and-run:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        activate-environment: seidart
        environment-file: seidart-environment.yml
        auto-activate-base: false

    - name: Verify Conda installation
      run: conda info

    - name: Activate Conda environment
      run: conda activate seidart

    - name: Run bash script
      run: |
        bash ./paths.sh
