# This is a GitHub Actions workflow configuration for testing SeidarT project 
# using a Conda environment.

name: SeidarT CI for Mac

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14-arm64
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.9
          miniconda-version: "latest"
          environment-file: seidart-environment.yml
          activate-environment: seidart
      
      - name: Install Dependencies
        run: |
          conda env update --file seidart-environment.yml --name seidart
          conda activate seidart
          # Install JSON-Fortran using Conda
          conda install -c conda-forge json-fortran

      - name: Compile SeidarT Backend
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          make -j$(nproc)
          make BIN_PATH=build install

      - name: Run Tests
        run: |
          conda activate seidart
          cd build
          ctest --output-on-failure

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SeidarT-build-logs
          path: build/*.log
