name: Build Fortran Executables

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    timeout-minutes: 240  # Increased the timeout to 240 minutes (4 hours)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Compiler Tools and Dependencies
      run: |
        if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          # Install required tools directly via apt on Linux
          sudo apt-get update
          sudo apt-get install -y build-essential curl file git gfortran cmake
        elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          # On macOS, use Homebrew to install dependencies
          brew update
          brew install gfortran json-fortran
        fi

    - name: Compile Fortran Code 
      run: |
        echo "Current directory is:"
        pwd 
        ls -la 
        mkdir build
        conda info -s
        ls /usr/local/
        # bash ./build.sh
    
    - name: Upload Executable Artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: seidart_executables_${{ matrix.os }}
        path: src/executables/${{ matrix.os }}
