name: macOS Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install Dependencies
        run: |
          brew install gfortran json-fortran
          echo "Using GFortran from $(which gfortran)"

      - name: Compile and Test
        run: |
          make clean
          make
#          ./your_executable